name: Bug Report
title: "[BUG] "
description: Report a problem in nvim-lsp-ts-utils
labels: [bug]
body:

  - type: checkboxes
    id: faq-prerequisite
    attributes:
      label: FAQ
      options:
        - label: I have checked [troubleshooting](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils#troubleshooting) and it didn't resolve my problem.
          required: true

  - type: checkboxes
    id: issue-prerequisite
    attributes:
      label: Issues
      options:
        - label: I have checked [existing issues](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/issues?q=is%3Aissue+) and there are no issues with the same problem.
          required: true

  - type: input
    attributes:
      label: "Neovim Version"
      description: "`nvim --version`:"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "A description of the behavior you expected. May optionally include logs, images, or videos."
    validations:
      required: true

  - type: dropdown
    id: help
    attributes:
      label: "Help"
      description: "Would you be able to resolve this issue by submitting a pull request?"
      options:
        - "Yes"
        - "Yes, but I don't know how to start. I would need guidance (check question below)"
        - "No"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Implementation help"
      description: "If you selected yes in the last question please specify what you would need help with in order to fix this."
    validations:
      required: false
